# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1350254826);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.installCache", "[]");
user_pref("extensions.lastAppVersion", "2.0");
user_pref("extensions.lastPlatformVersion", "15.0");
user_pref("pencil.config.collectionPane.floating", false);
user_pref("pencil.config.dev.stencil.path", "none");
user_pref("pencil.config.painterPropertyMap", "fillColor,foreColor,textColor,strokeColor,borderColor,strokeStyle,textAlign,textFont,shadowStyle,shadowColor,withBlur,withShadow,textPadding,startFillColor,endFillColor");
